files: ^(privacy_api/|tests/|setup.py)
repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.6

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
    -   id: isort
        args: [--atomic, --recursive]

  - repo: https://github.com/PyCQA/pylint
    rev: pylint-2.4.4
    hooks:
    -   id: pylint
        name: pylint-src
        additional_dependencies: [requests, attrs, marshmallow]
        files: ^privacy_api/
        args:
          - --disable=bad-continuation
          - --disable=too-many-arguments
          - --disable=line-too-long
          - --disable=too-many-instance-attributes

  - repo: https://github.com/PyCQA/pylint
    rev: pylint-2.4.4
    hooks:
    -   id: pylint
        name: pylint-tests
        additional_dependencies: [requests, attrs, marshmallow, pytest]
        files: ^tests/
        args: 
          - --disable=missing-function-docstring
          - --disable=missing-module-docstring
          - --disable=redefined-outer-name
          - --disable=unused-argument
          - --disable=wrong-import-order

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
    -   id: mypy
        files: ^privacy_api/.*$
