#!/usr/bin/env bash
set -xeuo pipefail

. "$(dirname $0)/common"

echo "+ $@"
find . -type d -name '__pycache__' -exec rm -rf {} +
find . -type d -name '*.egg-info' -exec rm -rf {} +
find . -type f -name '*.py[co]' -exec rm -f {} +
find . -name '*~' -exec rm -f {} +
